### ISSUE TITLE
Example of how to analyze test / experiements?

### ISSUE THREAD

**Issue by jblotus** [fromAtoB/vue-a2b#8]
Hey there, this looks really cool. I've been looking for a way to a/b test vue code (well marketing dept has). We are using google analytics w/ optimize on non-vue pages. I was curious how I could use something like this and collect analytics of which split test were more successful. Sorry for the novice question. Thanks!

**Comment by softbeehive** [comment]
Hi @jblotus,
we are using vue-a2b & Google Analytics. Basically we push the data layer events depending on the selected test variant.

```
// Track A-B tests
export const trackABtest = (name, variant) => {
  dataLayer({
    category: 'hobbit ab test',
    action: name,
    label: variant
  })
}
```

Then in component where you run the A-B test
```
import { trackABtest } from '../api/dataLayer'
// ...
beforeCreate () {
  const choice = this.$abtest('mobile-optimization', {optimized: 1, baseline: 1})
  const name = 'payment mobile optimization'
  trackABtest(name, choice)
}
```

In Google Analytics you can create a `segment` with advanced conditions
<img width="1147" alt="screen shot 2017-10-02 at 14 16 15" src="https://user-images.githubusercontent.com/1150276/31076849-886c0e5e-a77c-11e7-8b27-60b6bbcc5e79.png">

I hope it helps
